# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.0-116-ga996276
_src_path: https://github.com/usnistgov/cookiecutter-nist-python.git
command_line_interface: none
conda_channel: wpk-nist
email: wpk@nist.gov
full_name: William P. Krekelberg
github_username: wpk-nist-gov
project_name: mypackage
project_short_description: All the boilerplate you need to create a Python package.
project_slug: mypackage
pypi_username: wpk-nist
sphinx_theme: sphinx_book_theme
sphinx_use_autodocsumm: true
year: '2025'
