name: analphipy-env
channels:
    - conda-forge
    - wpk-nist
dependencies:
    - python=3.9
    - numpy
    - scipy
    # because using scm versioning
    - setuptools>=38.4
    # cli
    - typing-extensions
    - custom-inherit
    - attrs
