channels:
  - conda-forge
  - wpk-nist
dependencies:
  - MonkeyType
  - attrs
  - custom-inherit
  - ipykernel
  - ipython
  - matplotlib
  - module-utilities
  - mypy
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - pytest-mypy
  - pytest-xdist
  - python>=3.8
  - scipy
  - setuptools-scm
  - typing-extensions
  - pip:
      - mypy-extensions
      - pytest-monkeytype
name: analphipy-env
