# This file is for setting user specific config for use
# with nox and other project tools and applications.
#
# THIS FILE SHOULD NOT BE TRACKED BY GIT!!!!
#
# Example usage:
#
# [nox.python]
# paths = ["~/.conda/envs/python-3.*/bin"]
#
# [tool.pyproject2conda.envs.dev]
# extras = ["dev-complete"]
[nox.python]
paths = ["~/.conda/envs/python-3.*/bin"]

[tool.pyproject2conda.envs.dev]
extras = ["dev", "nox"]
