channels:
    - conda-forge
dependencies:
    - matplotlib
    - pandas
    - pip
    - pip:
            - pyenchant
            # TODO: something goes wonky with sphinx-book-theme and higher versions of sphinx
            - ghp-import
            - sphinx
            ## themes
            # sphinx_rtd_theme
            # sphinx-material
            # sphinx-book-theme
            ## notebook
            # nbsphinx
            - ipython
            - setuptools-scm
            ## optionals
            # sphinx-design
            - sphinx-copybutton
            - sphinxcontrib-spelling
            # sphinxext-rediraffe
            ## autobuild
            - sphinx-autobuild
            ## myst
            # myst-parser
            - myst-nb
            - autodocsumm
            # ensure most recent versions
            - sphinx-book-theme
